{% set name = "pymatriz" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 02bee48007c70a31abb958c7a745b17bfd92bd919114ed952e3150eb63f98ff9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - lxml
    - pandas
    - pip
    - python
    - requests
    - simplejson
    - websocket-client
  run:
    - lxml
    - pandas
    - python
    - requests
    - simplejson
    - websocket-client

test:
  imports:
    - pymatriz

about:
  home: "https://github.com/ggallohernandez/pymatriz"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Python connector for Primary DMA (Matriz) Rest and Websocket APIs."
  dev_url: https://github.com/ggallohernandez/pymatriz
  doc_url: https://pypi.python.org/pypi/pymatriz
  doc_source_url: https://github.com/ggallohernandez/pymatriz/blob/master/README.rst

extra:
  recipe-maintainers:
    - ggallohernandez
